// 口试具体例子库

const EXAMPLES_MAP = [
  {
    topic: '健康饮食与生活习惯',
    color: '#d35400',
    tip: 'Examiners want SPECIFIC initiatives by name. Don\'t just say "the government promotes healthy eating" — name the label system, the school programme, the app. Also use the 三高 term and connect junk food → chronic disease as a chain.',
    examples: [
      { label: 'Nutri-Grade 饮料分级', text: '政府强制推行Nutri-Grade饮料标签制度，将含糖饮料分为A至D四个等级，并规定D级饮料不得在媒体上做广告宣传，促使饮料商改良配方，减少糖分含量。' },
      { label: '学校健康餐食计划', text: '教育部推出「健康学校餐食计划」（Healthy Meals in Schools Programme），要求学校食堂摊位提供含蔬菜、水果和全麦食品的均衡膳食，从小培养学生健康的饮食习惯。' },
      { label: '较健康选择标志', text: '保健促进局（HPB）在超市和小贩中心推广「较健康选择标志」（Healthier Choice Symbol），鼓励消费者选择全麦、低糖、低脂肪的食品，让健康饮食的选择变得一目了然。' },
      { label: '慢性病年轻化（三高）', text: '根据调查，长期摄入高糖、高盐、高脂肪的食物，不仅会导致过度肥胖，还会提高患糖尿病、高血压、高胆固醇（俗称「三高」）等慢性疾病的风险，而且这些疾病正呈现年轻化的趋势。' },
      { label: 'Healthy 365 应用程序', text: '政府推出Healthy 365手机应用程序，鼓励国人追踪每日步数与饮食记录，并透过「全国健步大挑战」（National Steps Challenge），以积分奖励的方式激励国人保持运动习惯。' },
    ],
  },
  {
    topic: '心理健康与抗压能力',
    color: '#8e44ad',
    tip: 'Use the 1-in-3 statistic as your opening proof-point. Name SOS (1767), IMH, and Peer Support by name. The 草莓族 label is useful but balance it with empathy — acknowledge the pressure is real before criticising resilience levels.',
    examples: [
      { label: '1/3 青少年忧郁统计', text: '根据研究显示，每三名10至18岁的青少年中，就有一人出现明显的忧郁和焦虑症状。这一数据说明青少年的心理健康问题已是刻不容缓、不容忽视的社会课题。' },
      { label: '新加坡援人协会（SOS）热线1767', text: '新加坡援人协会（SOS）提供24小时情绪支持与危机干预服务，热线电话为1767。当青少年面对无法独自承受的情绪压力时，拨打这条热线便能获得即时的专业援助。' },
      { label: '心理卫生学院（IMH）', text: '心理卫生学院（IMH）为有需要的人士提供专业的心理评估与精神疾病治疗，打破了「心理疾病是个人软弱」的误解，让更多人愿意主动寻求专业帮助。' },
      { label: '学校同侪支援计划', text: '许多学校推行「同侪支援计划」（Peer Support Leaders），培训学生担任同侪辅导员，因为同学之间更容易设身处地理解彼此，能有效降低同学向外求助的心理门槛。' },
      { label: '立化中学健康生活方式月', text: '立化中学将每年四月定为「健康生活方式月」，举办全校体操、引体向上、跳绳等体能挑战，让学生通过运动释放压力，培养规律锻炼的好习惯。' },
      { label: '全科目编班减压（Full SBB）', text: '教育部推行全科目编班（Full SBB），取消了「快捷」和「普通」源流的标签，让学生根据各科目能力选择适合的程度修读，减少「唯分数论」带来的自我否定与心理压力。' },
    ],
  },
  {
    topic: '科技与数字健康',
    color: '#2c3e50',
    tip: 'Avoid generic "technology is good/bad". Use specific Smart Nation examples and give both a benefit AND a risk for each. FOMO and dopamine addiction are high-value terms — explain them briefly when you use them.',
    examples: [
      { label: 'NaviLens 应用（视障导航）', text: '地铁运营商SMRT在兀兰综合交通中心试行NaviLens应用程序，透过彩色标签与语音辅助，让视障通勤者能够独立导航，无需依赖他人，大大提升了公共交通的无障碍程度。' },
      { label: '送货机器人 IM-Aiden', text: '本地研发的送货机器人IM-Aiden能自动穿梭于组屋区，搭乘电梯并避开障碍物，为行动不便或独居年长者配送物资，显著提升了他们的生活自主性，减轻了社区护理人员的负担。' },
      { label: '数码乐龄计划（Seniors Go Digital）', text: '政府推行「数码乐龄计划」，派遣数码大使走进社区和巴刹，手把手教导银发族使用智能手机、电子支付和识别网络诈骗，以期缩小数码鸿沟，让年长者不被时代淘汰。' },
      { label: 'Student Learning Space（SLS）', text: '教育部推出Student Learning Space（SLS）平台，让学生可以随时随地进行自主学习，个人化的学习资源也帮助不同程度的学生按照自己的节奏掌握知识。' },
      { label: '社交媒体的 FOMO 与容貌焦虑', text: '社交媒体的「滤镜」效应让网上呈现的生活看起来无比完美，青少年心智尚未成熟，容易盲目攀比，从而产生「容貌焦虑」和「错失恐惧症」（FOMO），长期沉迷其中，更会因多巴胺成瘾而损害深度思考与专注的能力。' },
      { label: '虚拟体育（Virtual Sports）', text: '虚拟体育如模拟赛车、室内虚拟高尔夫等，打破了传统运动中性别、年龄与体能的限制，让更多人以低门槛的方式参与体育活动；然而，高昂的硬件成本与网络延迟等问题，也限制了其普及性。' },
    ],
  },
  {
    topic: '公共卫生与社区责任',
    color: '#c0392b',
    tip: 'This topic rewards specificity: name the agency (HSA, LTA, SMRT) + the measure + the target group. The SMRT/MINDS partnership and the "Can I have a seat?" lanyard are both specific enough to impress examiners.',
    examples: [
      { label: 'SMRT 与 MINDS 合作（智障人士）', text: '为了创造对智障人士更包容的环境，社服机构MINDS与地铁运营商SMRT合作，教导智障人士如何在巴士站和地铁站独立通行，同时培训SMRT员工以正确的方式协助有需要的乘客，体现了公共交通无障碍化的精神。' },
      { label: '陆交局「能否为我让座」挂绳', text: '陆路交通管理局（LTA）推出「能否为我让座」（Can I Have A Seat?）计划，让患有隐性疾病或残障人士可以向地铁站索取挂绳或贴纸，更容易在公共交通上获得他人让座，有效提升了公共交通的包容性。' },
      { label: '失智症友善地铁站（98个）', text: '截至2022年，SMRT管理的98个地铁站均已成为「失智症友善站」（Dementia Go-To Points），经过培训的工作人员能及时发现并援助迷路的失智症患者，协助他们联系家属或找到回家的路。' },
      { label: '电子烟伪装问题', text: '尽管新加坡法律严禁进口和持有电子烟，但由于其外形常被伪装成U盘、荧光笔等文具，加上网络上大量虚假宣传声称电子烟「无害」，导致青少年吸食电子烟的现象在校园中暗流涌动。' },
      { label: 'Healthier SG（健康SG）', text: '政府推出Healthier SG计划，鼓励国人固定看同一名全科医生，建立长期的健康档案并做定期体检，将医疗重心从「治病」转向「防病」，以期减轻长期慢性病对医疗系统的负担。' },
    ],
  },
  {
    topic: '社会包容性与弱势群体',
    color: '#1abc9c',
    tip: 'Inclusivity answers score higher when you cover at least two distinct groups (elderly + disabled, or low-income + foreigners). Name specific facilities or NGOs — they show Singapore knowledge.',
    examples: [
      { label: '活跃乐龄中心（超过200家）', text: '全岛现有超过200家活跃乐龄中心，大多建在组屋底层，让年长者步行即可参与郊游、健康讲座和兴趣小组等活动。研究显示，每五名61岁以上国人中就有两人感到孤独，这些中心正是帮助他们建立社交网络、促进心理健康的重要据点。' },
      { label: 'Golden Ginger 乐龄中心', text: '在Golden Ginger乐龄组屋，乐龄活动中心就设在组屋底层，参与活动的年长者往往都是彼此的邻居，因此这些活动不仅促进了健康，更加深了邻里之间的感情与信任。' },
      { label: 'JamPacked 食物银行（武吉巴督）', text: '武吉巴督的JamPacked食物银行由新加坡回教传教协会与基层组织合作开设，以「各取所需」的方式让低收入家庭使用礼券自行「购物」，选择所需物品，避免浪费，体现了对弱势群体尊严的尊重。' },
      { label: 'ComCare 社区援助计划', text: '政府在社会及家庭发展部（MSF）下设立ComCare计划，为低收入家庭提供经济援助、医疗补助和子女教育津贴。政府还在各组屋区设立社会服务中心（SSO），主动寻找和帮助有需要的家庭，做到精准扶贫。' },
      { label: 'SG Cares 义工综合中心', text: '政府透过「关爱新加坡行动」（SG Cares），在全岛各市镇设立义工综合中心，将学校、企业、社区和慈善机构结合起来，让国人能就近参与志愿服务，把助人行善变成一种生活常态。' },
      { label: '组屋种族比例政策（EIP）', text: '新加坡政府自1989年起推行组屋种族比例政策（EIP），确保不同种族的居民均匀分布在各个组屋区，防止形成单一族群社区。例如，实龙岗区的华族配额为84%，马来族22%，印度族及其他少数族裔12%，以此促进日常的跨族群互动。' },
    ],
  },
  {
    topic: '环保与可持续发展',
    color: '#27ae60',
    tip: 'Singapore Green Plan 2030 is your anchor — mention it, then drill down to ONE specific initiative with details. Bottle Return Scheme is very current. Always end with personal action (BYOB) to show civic awareness.',
    examples: [
      { label: '新加坡2030年绿色发展蓝图', text: '新加坡制定了《2030年绿色发展蓝图》，目标是到2050年实现净零碳排放。蓝图涵盖能源重置与减碳、循环经济与废弃物管理、大自然城市、可持续交通与建筑等多个领域，体现了政府多管齐下应对气候变化的决心。' },
      { label: '瓶罐退费制度（2024年）', text: '新加坡于2024年推出瓶罐退费制度，消费者购买饮料时需支付额外押金，归还空瓶或空罐后可取回押金。此举通过经济激励手段，有效促进国人养成回收饮料容器的习惯，减少废弃物进入垃圾填埋场。' },
      { label: '四大水喉（NEWater占约40%）', text: '为应对水资源匮乏的挑战，新加坡建立了「四大水喉」：进口水、收集的雨水、新生水（NEWater）和淡化水。其中新生水将再生水通过高科技提纯而成，现已占新加坡供水量的约40%，充分体现了「未雨绸缪」的长远眼光。' },
      { label: '购物袋收费政策（2023年）', text: '自2023年起，新加坡超市对一次性购物袋收费，通过经济杠杆促使消费者自带购物袋，逐渐改变「习惯性索取塑料袋」的消费文化，推动「自备袋」（BYOB）成为社会新风尚。' },
      { label: 'Walking Trails @ CDC', text: '五个社区发展理事会（CDC）与政府科技局合作，推出「齐步乐探计划」（Walking Trails @ CDC），结合实体步行与手机互动游戏，让居民在锻炼身体的同时探索社区历史文化与自然遗产。' },
    ],
  },
  {
    topic: '传统文化与多元文化保育',
    color: '#e74c3c',
    tip: 'Hawker culture UNESCO listing is your strongest anchor. Use the 3R conservation principle (Retention, Restoration, Reconstruction) for heritage building questions. For festivals, name specific rituals — not just the festival name.',
    examples: [
      { label: '小贩文化列入联合国非物质文化遗产（2020年）', text: '新加坡小贩文化已于2020年成功申报联合国教科文组织人类非物质文化遗产代表作名录。这不仅是对新加坡多元饮食文化的国际认可，更凸显了小贩中心作为不同种族居民日常交流场所的深厚社会意义。' },
      { label: '国家非物质文化遗产名录', text: '新加坡国家文物局建立了国家非物质文化遗产清单，涵盖娘惹刺绣、华族木偶戏、旗袍剪裁、捞鱼生（Lo Hei）等传统手工技艺与饮食文化，系统记录并传承这些正面临「后继无人」危机的珍贵文化瑰宝。' },
      { label: 'SG Culture Pass（100元文化通行证）', text: '政府推出面额100元的「文化通行证」（SG Culture Pass），鼓励国人使用津贴参与本地艺术和文化演出、博物馆展览及文化遗产体验活动，以实际行动推动国人接触和认识本土文化。' },
      { label: '历史建筑活化——3R原则', text: '新加坡在修缮历史古迹时，遵循「保留、修复、重构」（Retention, Restoration, Reconstruction）原则，保留建筑外观历史风貌的同时，赋予其新的现代用途。例如，由前最高法院和政府大厦改建而成的国家美术馆，既承载历史记忆，又成为展现本地艺术的文化平台。' },
      { label: '种族和谐日（Racial Harmony Day）', text: '每年的种族和谐日鼓励学校和社区举办文化交流活动，如穿着各族传统服装、品尝各族传统美食等，帮助年轻一代在轻松愉快的氛围中增进对不同文化的理解与尊重，从小培育多元文化意识。' },
      { label: '开斋节 Open House 传统', text: '每逢开斋节，马来家庭有敞开家门（Open House）款待各族友人的传统，亲友间也会互相寻求宽恕、修复关系。这种「以和为贵」的节日精神，正是新加坡多元种族和谐共处的最佳缩影。' },
    ],
  },
  {
    topic: '乐龄社会与跨代共融',
    color: '#7f8c8d',
    tip: 'Show awareness of the problem scale (statistics) AND name concrete interventions. The intergenerational bonding angle — preschool next to eldercare — is particularly strong as it shows creative policy thinking.',
    examples: [
      { label: '海军部村庄（跨代共融）', text: '获奖建筑「海军部村庄」（Kampung Admiralty）将医疗中心、托儿所和城市农场整合在同一建筑之内，让幼童与年长者在日常生活中自然互动，打破年龄隔阂，体现了「跨代共融」的创新设计理念。' },
      { label: '关爱乐龄大使（Silver Generation Ambassadors）', text: '政府培训「关爱乐龄大使」，由义工主动登门拜访独居年长者，了解他们的需求并协助连接社区服务，让那些不善于主动求助的年长者也能得到关怀，避免因社交孤立而产生心理健康问题。' },
      { label: '失智症友善社区（CARA 应用）', text: '新加坡积极推动「失智症友善社区」建设，Dementia Singapore推出CARA应用程序，为失智症患者及看护者提供资源、社区活动信息和紧急联络功能，同时也培训商店、巴士司机等社区人员识别和协助失智症患者。' },
      { label: '看护者培训津贴（Caregivers Training Grant）', text: '许多年长者的情绪问题源于「看护者压力」，政府因此提供看护者培训津贴（Caregivers Training Grant）以及暂托服务（Respite Care），让长期照顾年迈父母或伴侣的家庭成员得以喘息，避免两代人同时被压垮。' },
      { label: '孤独感调查——每5人中有2人', text: '根据杜克-新加坡国立大学研究显示，每五名61岁以上的国人中，就有两人感到孤独。这一数据印证了「活跃乐龄」政策的必要性——单纯的物质供养并不够，年长者同样需要社交连结与精神关怀。' },
    ],
  },
  {
    topic: '青少年成长与教育改革',
    color: '#f39c12',
    tip: 'FSBB and removal of streaming are your two strongest Singapore-specific examples. SkillsFuture shows lifelong learning. Link to 因材施教 to show language sophistication alongside factual knowledge.',
    examples: [
      { label: '全科目编班——取消源流（2024年）', text: '教育部于2024年全面落实全科目编班（Full Subject-Based Banding），彻底取消实施数十年的「快捷」和「普通」源流分班制度，让学生根据各科目的实际能力选择适合的程度修读，真正做到因材施教，也减少了因源流标签带来的自我设限。' },
      { label: '取消年中考试', text: '教育部逐步取消中小学的年中考试，将原来用于备考的时间改为探究式学习和自主学习，鼓励学生从「为考试而学」转变为「为成长而学」，培养真正的求知欲与终身学习的态度。' },
      { label: 'SkillsFuture 终身学习', text: '政府推行SkillsFuture计划，为国人提供各类技能培训津贴，涵盖数码科技、人工智能、商业和职业转换课程。这体现了「终身学习」的国家理念——学习不应止于毕业，而应贯穿整个职业生涯。' },
      { label: '品格与公民教育（CCE）', text: '学校将品格与公民教育（CCE）列为必修课程，内容涵盖国家认同、社会责任、网络礼仪、心理健康和多元文化尊重，旨在培养不仅学业出色、更有责任感和同理心的完整公民。' },
      { label: 'Values in Action（VIA）义工服务', text: '学校通过Values in Action（VIA）义工计划，鼓励学生走出课室参与社区服务，如陪伴年长者、参与环保活动或协助残障人士，让年轻人在实践中培养公民意识和回馈社会的精神。' },
    ],
  },
  {
    topic: '友情、责任与公民意识',
    color: '#16a085',
    tip: 'The most impressive civic answers move from "rules" to "values" — argue that a good citizen acts rightly even when no one is watching or the law doesn\'t require it. Use the post-pandemic mask example as a case study for this argument.',
    examples: [
      { label: '国民服役（NS）与公民责任', text: '新加坡男性公民须服全职国民服役（National Service），这不仅是保卫国家的军事义务，更是培养年轻人纪律意识、团队精神和牺牲奉献精神的重要历程，是公民责任意识最具体的体现之一。' },
      { label: '全民防御日（Total Defence Day）', text: '每年2月15日是全民防御日，提醒国人新加坡须时刻保持警惕。全民防御涵盖军事、民事、经济、社会和心理防御五个层面，强调每个公民都是国家安全网络的一部分。' },
      { label: '守望相助：防骗全民防线', text: '新加坡诈骗案逐年攀升，许多年长者因不熟悉科技而蒙受巨大损失。政府强调，防骗不能只靠警察，更需要全社会「守望相助」——年轻人有责任主动教导长辈识别钓鱼短信和电话诈骗，将「独善其身」升华为「兼济天下」。' },
      { label: '强制归还托盘文化（2021年）', text: '新加坡从2021年起规定小贩中心食客必须自行归还餐盘，此举不仅减轻清洁工人的工作负担，更是培养国人「公共空间是共享责任」意识的重要一步。公德心不应依赖法律强制，而应发自内心。' },
      { label: '网络公审与Doxing法令（2021年）', text: '新加坡于2021年通过《保护网络骚扰法令》修订，将蓄意公布他人个人资料（「人肉搜索」，俗称Doxing）列为刑事罪行，正式确认网络世界并非法外之地，网民须为自己的言行负上法律责任。' },
    ],
  },
  {
    topic: '小人物大贡献',
    color: '#34495e',
    tip: 'ONE well-told real story beats three generic points. The 曾喆/911 story is your best anchor — use it. After the story, pivot to what it proves: greatness is about choices, not status. Then connect to the everyday heroes around us.',
    examples: [
      { label: '曾喆：911中的新加坡英雄', text: '曾喆原本只是一名在纽约工作的普通新加坡保险公司职员。2001年9月11日，他在世贸中心遭受恐怖袭击时，选择留下来协助同事逃生，最终不幸罹难。他的牺牲告诉我们：伟大不需要特殊的身份或地位，关键时刻的善良选择，才是定义一个人伟大之处的真正标准。' },
      { label: '地铁深夜维修人员', text: '每当我们安然入睡，地铁维修人员已深入隧道，清洗车厢、更换轨道、检查信号系统，确保数百万乘客翌日能安全出行。他们的贡献鲜少见报，却是城市正常运转不可或缺的支柱。' },
      { label: 'SPCA 企业健康计划', text: '新加坡防止虐待动物协会（SPCA）设有「企业健康计划」，安排曾被遗弃的动物到企业工作场所进行互动探访。这既提升了动物被领养的机会，也让员工在与动物互动的过程中缓解压力、促进心理健康。' },
      { label: 'Montfort Care 快乐厨房', text: '蒙福关爱（Montfort Care）在马林台组屋底层设立「快乐厨房」（Goodlife Makan），为独居年长者提供共享社区厨房，让他们在一起煮饭、吃饭的过程中结交邻居、建立感情，以一顿饭的温度对抗孤独。' },
      { label: 'JamPacked 食物银行义工', text: '武吉巴督JamPacked食物银行的义工们，默默将邻居和市民捐来的食物分门别类，再让低收入家庭用礼券「购物」自取所需。他们的付出不轰动、不显眼，却是许多家庭每个月温饱的保障。' },
    ],
  },
  {
    topic: '创新与建筑',
    color: '#9b59b6',
    tip: 'Describe the design detail AND explain what problem it solves — that\'s what makes an answer insightful rather than encyclopaedic. The NTU Hive passive cooling system is a detail most students don\'t know and will impress.',
    examples: [
      { label: 'NTU The Hive 被动冷气系统（小笼包教学楼）', text: '南洋理工大学的The Hive教学楼外形酷似一叠广式小笼包，但其创新之处不在外形，而在于它的「被动置换冷气系统」——没有传统空调出风口，而是通过地板下的管道释放冷水降温，冷空气自然下沉，热空气从无顶盖的中庭散出，节能率极高。' },
      { label: 'Oasia Hotel Downtown 垂直绿化', text: 'Oasia Hotel Downtown以抢眼的红色网状外墙著称，外墙上攀爬着21种不同的藤蔓植物，绿容率高达1100%，为城市提供的绿化面积是其占地面积的11倍；建筑中央镂空设计让整栋大楼全靠天然穿堂风保持凉爽，无需空调。' },
      { label: '皮克林宾乐雅酒店 零能耗空中花园', text: '皮克林宾乐雅酒店（Parkroyal Collection Pickering）外墙布满梯田式空中花园，花园的灌溉与照明全靠太阳能电池板和雨水收集系统维持，真正实现了「零能耗」空中花园，并显著降低市中心的热岛效应。' },
      { label: '国家美术馆——历史建筑活化', text: '新加坡国家美术馆由两栋历史建筑——前最高法院和前市政厅——翻新改建而成，在保留殖民地时期宏伟外观的同时，内部空间被赋予全新的艺术展览功能。这正是「活化」而非「冰封」历史的最佳诠释。' },
      { label: '复古市集与本地文创', text: '近年来，复古文化在本地年轻人中掀起热潮，他们在复古市集中展示个人收藏与融合东南亚元素的创意设计，将娘惹图案、殖民地建筑美学等本土传统转化为现代文创产品，让传统文化以年轻人喜欢的方式延续生命力。' },
    ],
  },
];
