// 口试具体例子库 — key terms bolded inline, no separate label line

const EXAMPLES_MAP = [
  {
    topic: '健康饮食与生活习惯',
    color: '#d35400',
    tip: 'Name the initiative specifically. Don\'t say "the government promotes healthy eating" — say Nutri-Grade, Healthier Choice Symbol, Healthy Meals in Schools. Use 三高 and connect junk food → chronic disease as a causal chain.',
    examples: [
      { text: '政府强制推行<b>Nutri-Grade饮料标签制度</b>，将含糖饮料分为A至D四个等级，并规定D级饮料不得在媒体上做广告宣传，促使饮料商改良配方，减少糖分含量。' },
      { text: '教育部推出<b>健康学校餐食计划</b>（Healthy Meals in Schools Programme），要求学校食堂摊位提供含蔬菜、水果和全麦食品的均衡膳食，从小培养学生健康的饮食习惯。' },
      { text: '保健促进局（HPB）在超市和小贩中心推广<b>较健康选择标志</b>（Healthier Choice Symbol），鼓励消费者选择全麦、低糖、低脂肪的食品，让健康饮食的选择变得一目了然。' },
      { text: '长期摄入高糖、高盐、高脂肪的食物，不仅会导致过度肥胖，还会提高患糖尿病、高血压、高胆固醇（俗称<b>「三高」</b>）等慢性疾病的风险，而且这些疾病正呈现年轻化的趋势。' },
      { text: '政府推出<b>Healthy 365手机应用程序</b>，鼓励国人追踪每日步数与饮食记录，并透过<b>全国健步大挑战</b>（National Steps Challenge），以积分奖励的方式激励国人保持运动习惯。' },
      { text: '政府推出<b>Healthier SG计划</b>，鼓励国人固定看同一名全科医生，建立长期健康档案并做定期体检，将医疗重心从「治病」转向「防病」，以期减轻慢性病对医疗系统的负担。' },
    ],
  },
  {
    topic: '心理健康与抗压能力',
    color: '#8e44ad',
    tip: 'Open with the 1-in-3 statistic — it immediately shows you\'ve done your research. Name SOS (1767) and IMH specifically. Balance 草莓族 criticism with empathy: acknowledge that pressure is real before critiquing resilience levels.',
    examples: [
      { text: '根据研究显示，<b>每三名10至18岁的青少年中，就有一人出现明显的忧郁和焦虑症状</b>，这一数据说明青少年的心理健康问题已是刻不容缓的社会课题。' },
      { text: '<b>新加坡援人协会（SOS）</b>提供24小时情绪支持与危机干预服务，热线电话为<b>1767</b>。当青少年面对无法独自承受的情绪压力时，拨打这条热线便能获得即时的专业援助。' },
      { text: '<b>心理卫生学院（IMH）</b>为有需要的人士提供专业的心理评估与精神疾病治疗，打破了「心理疾病是个人软弱」的误解，让更多人愿意主动寻求专业帮助。' },
      { text: '许多学校推行<b>同侪支援计划</b>（Peer Support Leaders），培训学生担任同侪辅导员，因为同学之间更容易设身处地理解彼此，能有效降低向外求助的心理门槛。' },
      { text: '立化中学将每年四月定为<b>「健康生活方式月」</b>，举办全校体操、引体向上、跳绳等体能挑战，让学生通过运动释放压力，培养规律锻炼的好习惯。' },
      { text: '教育部推行<b>全科目编班（Full SBB）</b>，取消了「快捷」和「普通」源流的标签，让学生根据各科目能力选择适合的程度修读，减少「唯分数论」带来的自我否定与心理压力。' },
      { text: '<b>飞跃社区服务（Fei Yue）</b>和<b>关怀机构（Care Corner）</b>设有专门的青少年辅导热线，提供心理疏导与家庭支持，为不愿前往医院求助的青少年提供了更亲切的第一步。' },
    ],
  },
  {
    topic: '科技与数字健康',
    color: '#2c3e50',
    tip: 'Avoid generic "technology is good/bad". Use specific Smart Nation examples and give both a benefit AND a risk for each one. FOMO and dopamine addiction are high-value terms — explain them briefly when you use them.',
    examples: [
      { text: '地铁运营商SMRT在兀兰综合交通中心试行<b>NaviLens应用程序</b>，透过彩色标签与语音辅助，让视障通勤者能够独立导航，无需依赖他人，大大提升了公共交通的无障碍程度。' },
      { text: '本地研发的<b>送货机器人IM-Aiden</b>能自动穿梭于组屋区，搭乘电梯并避开障碍物，为行动不便或独居年长者配送物资，显著提升了他们的生活自主性，减轻了社区护理人员的负担。' },
      { text: '政府推行<b>数码乐龄计划（Seniors Go Digital）</b>，派遣数码大使走进社区和巴刹，手把手教导银发族使用智能手机、电子支付和识别网络诈骗，以期缩小数码鸿沟，让年长者不被时代淘汰。' },
      { text: '教育部推出<b>Student Learning Space（SLS）</b>平台，让学生可以随时随地进行自主学习，个人化的学习资源也帮助不同程度的学生按照自己的节奏掌握知识。' },
      { text: '社交媒体的「滤镜」效应让网上呈现的生活看起来无比完美，青少年容易盲目攀比，从而产生<b>「容貌焦虑」和「错失恐惧症」（FOMO）</b>，长期沉迷其中，更会因<b>多巴胺成瘾</b>而损害深度思考与专注的能力。' },
      { text: '<b>虚拟体育</b>如模拟赛车、室内虚拟高尔夫等，打破了传统运动中性别、年龄与体能的限制，让更多人以低门槛的方式参与体育活动；然而，高昂的硬件成本与网络延迟，也限制了其普及性。' },
    ],
  },
  {
    topic: '公共卫生与社区公德',
    color: '#c0392b',
    tip: 'Name the agency + the measure + the target group in one sentence. The SMRT/MINDS partnership and the LTA lanyard scheme are specific enough to impress. For civic-mindedness questions, argue that law not mandating something ≠ morality not requiring it.',
    examples: [
      { text: '为了创造对智障人士更包容的环境，社服机构<b>MINDS与地铁运营商SMRT合作</b>，教导智障人士如何在车站独立通行，同时培训SMRT员工协助有需要的乘客，体现了公共交通无障碍化的精神。' },
      { text: '陆路交通管理局（LTA）推出<b>「能否为我让座」挂绳计划</b>，让患有隐性疾病或残障人士可以向地铁站索取挂绳或贴纸，更容易在公共交通上获得他人让座。' },
      { text: '截至2022年，SMRT管理的<b>98个地铁站均已成为「失智症友善站」</b>（Dementia Go-To Points），经过培训的工作人员能及时发现并援助迷路的失智症患者，协助他们联系家属或找到回家的路。' },
      { text: '尽管新加坡法律严禁进口和持有电子烟，但由于其外形常被伪装成U盘、荧光笔等文具，加上网络虚假宣传其「无害」，导致<b>青少年吸食电子烟</b>的现象在校园中暗流涌动。' },
      { text: '新加坡从2021年起规定小贩中心食客必须<b>自行归还餐盘</b>，此举不仅减轻清洁工人的工作负担，更是培养国人「公共空间是共享责任」意识的重要一步。公德心不应依赖法律强制，而应发自内心。' },
      { text: '新加坡于2021年通过《保护网络骚扰法令》修订，将蓄意公布他人个人资料（<b>「人肉搜索」Doxing</b>）列为刑事罪行，正式确认网络世界并非法外之地，网民须为自己的言行负上法律责任。' },
    ],
  },
  {
    topic: '社会包容性与弱势群体',
    color: '#1abc9c',
    tip: 'Score higher by covering at least two distinct groups (e.g. elderly + disabled, OR low-income + foreigners). Name specific facilities or NGOs — generic statements about "helping the needy" don\'t score.',
    examples: [
      { text: '全岛现有<b>超过200家活跃乐龄中心</b>，大多建在组屋底层，让年长者步行即可参与郊游、健康讲座和兴趣小组。研究显示，每五名61岁以上国人中就有两人感到孤独，这些中心是帮助他们建立社交网络的重要据点。' },
      { text: '在<b>Golden Ginger乐龄组屋</b>，乐龄活动中心就设在底层，参与活动的年长者往往都是彼此的邻居，因此这些活动不仅促进了健康，更加深了邻里之间的感情与信任。' },
      { text: '武吉巴督的<b>JamPacked食物银行</b>由新加坡回教传教协会与基层组织合作开设，以「各取所需」的方式让低收入家庭使用礼券自行「购物」，选择所需物品，避免浪费，体现了对弱势群体尊严的尊重。' },
      { text: '政府在社会及家庭发展部（MSF）下设立<b>ComCare计划</b>，为低收入家庭提供经济援助、医疗补助和子女教育津贴，并在各组屋区设立社会服务中心（SSO），主动寻找有需要的家庭，做到精准扶贫。' },
      { text: '政府透过<b>「关爱新加坡行动」（SG Cares）</b>在全岛各市镇设立义工综合中心，将学校、企业、社区和慈善机构结合起来，让国人能就近参与志愿服务，把助人行善变成一种生活常态。' },
      { text: '新加坡政府自1989年起推行<b>组屋种族比例政策（EIP）</b>，确保不同种族的居民均匀分布在各个组屋区。例如，实龙岗区的华族配额为84%，马来族22%，印度族12%，以此促进日常的跨族群互动。' },
    ],
  },
  {
    topic: '环保与可持续发展',
    color: '#27ae60',
    tip: 'Anchor with the Green Plan 2030, then drill down to ONE specific initiative with a concrete detail. The Bottle Return Scheme (2024) is very current. Always close with a personal-action line (BYOB, refuse straws) to show civic awareness.',
    examples: [
      { text: '新加坡制定了<b>《2030年绿色发展蓝图》</b>，目标是到2050年实现净零碳排放，涵盖能源重置与减碳、循环经济与废弃物管理、大自然城市、可持续交通与建筑等多个领域。' },
      { text: '新加坡于2024年推出<b>瓶罐退费制度</b>，消费者购买饮料时须支付额外押金，归还空瓶或空罐后可取回押金，通过经济激励手段有效促进国人养成回收饮料容器的习惯。' },
      { text: '为应对水资源匮乏，新加坡建立了<b>「四大水喉」</b>：进口水、收集的雨水、<b>新生水（NEWater）</b>和淡化水。新生水现已占供水量约40%，充分体现了「未雨绸缪」的长远眼光。' },
      { text: '自2023年起，新加坡超市对<b>一次性购物袋收费</b>，通过经济杠杆促使消费者自带购物袋，推动<b>「自备袋」（BYOB）</b>成为社会新风尚，逐渐改变「习惯性索取塑料袋」的消费文化。' },
      { text: '五个<b>社区发展理事会（CDC）</b>与政府科技局合作推出<b>「齐步乐探计划」（Walking Trails @ CDC）</b>，结合实体步行与手机互动游戏，让居民在锻炼身体的同时探索社区历史文化与自然遗产。' },
      { text: '实马高垃圾岛（Semakau Landfill）预计将于2035年前后填满，这正是政府大力推动<b>「零废弃物」（Zero Waste）</b>和资源回收的背景——一旦失去唯一的垃圾填埋场，新加坡将面临严峻的废弃物管理危机。' },
    ],
  },
  {
    topic: '传统文化与多元文化保育',
    color: '#e74c3c',
    tip: 'The UNESCO hawker culture listing (2020) is your strongest anchor — use it. Use the 3R principle (Retention, Restoration, Reconstruction) for heritage building questions. For festivals, name specific rituals, not just the festival name.',
    examples: [
      { text: '<b>新加坡小贩文化</b>已于2020年成功申报<b>联合国教科文组织人类非物质文化遗产</b>代表作名录，不仅是对多元饮食文化的国际认可，更凸显了小贩中心作为不同种族居民日常交流场所的深厚社会意义。' },
      { text: '新加坡国家文物局建立了<b>国家非物质文化遗产清单</b>，涵盖娘惹刺绣、华族木偶戏、旗袍剪裁、捞鱼生（Lo Hei）等传统技艺，系统记录并传承这些正面临「后继无人」危机的文化瑰宝。' },
      { text: '政府推出面额100元的<b>「文化通行证」（SG Culture Pass）</b>，鼓励国人使用津贴参与本地艺术演出、博物馆展览及文化遗产体验活动，以实际行动推动国人接触和认识本土文化。' },
      { text: '新加坡在修缮历史古迹时，遵循<b>「保留、修复、重构」（3R）原则</b>，保留建筑外观历史风貌的同时，赋予其新的现代用途。由前最高法院和政府大厦改建而成的<b>国家美术馆</b>正是最佳例证。' },
      { text: '每年的<b>种族和谐日（Racial Harmony Day）</b>鼓励学校和社区举办文化交流活动，如穿着各族传统服装、品尝各族传统美食等，帮助年轻一代在轻松愉快的氛围中增进对不同文化的尊重。' },
      { text: '每逢开斋节，马来家庭有<b>敞开家门（Open House）</b>款待各族友人的传统，亲友间也会互相寻求宽恕、修复关系。这种「以和为贵」的节日精神，正是新加坡多元种族和谐共处的最佳缩影。' },
    ],
  },
  {
    topic: '乐龄社会与跨代共融',
    color: '#7f8c8d',
    tip: 'Show the problem scale (the 2-in-5 loneliness statistic) then name concrete interventions. The intergenerational design angle — preschool next to eldercare — is particularly impressive as it shows creative policy thinking.',
    examples: [
      { text: '获奖建筑<b>「海军部村庄」（Kampung Admiralty）</b>将医疗中心、托儿所和城市农场整合在同一建筑之内，让幼童与年长者在日常生活中自然互动，打破年龄隔阂，体现了「跨代共融」的创新设计理念。' },
      { text: '政府培训<b>「关爱乐龄大使」（Silver Generation Ambassadors）</b>，由义工主动登门拜访独居年长者，了解他们的需求并协助连接社区服务，让那些不善于主动求助的年长者也能得到关怀。' },
      { text: '<b>Dementia Singapore</b>推出<b>CARA应用程序</b>，为失智症患者及看护者提供资源、社区活动信息和紧急联络功能，同时也培训商店、巴士司机等社区人员识别和协助失智症患者。' },
      { text: '政府提供<b>看护者培训津贴（Caregivers Training Grant）</b>以及<b>暂托服务（Respite Care）</b>，让长期照顾年迈父母或伴侣的家庭成员得以喘息，避免看护者与被看护者同时因压力而崩溃。' },
      { text: '根据杜克-新加坡国立大学研究显示，<b>每五名61岁以上的国人中，就有两人感到孤独</b>。这一数据印证了「活跃乐龄」政策的必要性——单纯的物质供养并不够，年长者同样需要社交连结与精神关怀。' },
    ],
  },
  {
    topic: '青少年成长与教育改革',
    color: '#f39c12',
    tip: 'Full SBB (2024) and removal of mid-year exams are your strongest Singapore-specific examples. Link them to 因材施教 to show language sophistication. SkillsFuture demonstrates the lifelong-learning philosophy.',
    examples: [
      { text: '教育部于2024年全面落实<b>全科目编班（Full Subject-Based Banding）</b>，彻底取消实施数十年的「快捷」和「普通」源流分班制度，让学生根据各科目的实际能力选择适合的程度修读，真正做到因材施教。' },
      { text: '教育部逐步<b>取消中小学年中考试</b>，将原来用于备考的时间改为探究式学习和自主学习，鼓励学生从「为考试而学」转变为「为成长而学」，培养真正的求知欲与终身学习的态度。' },
      { text: '政府推行<b>SkillsFuture计划</b>，为国人提供各类技能培训津贴，涵盖数码科技、人工智能、商业和职业转换课程，体现了「终身学习」的国家理念——学习不应止于毕业，而应贯穿整个职业生涯。' },
      { text: '学校将<b>品格与公民教育（CCE）</b>列为必修课程，内容涵盖国家认同、社会责任、网络礼仪、心理健康和多元文化尊重，旨在培养不仅学业出色、更有责任感和同理心的完整公民。' },
      { text: '学校通过<b>Values in Action（VIA）义工计划</b>，鼓励学生走出课室参与社区服务，如陪伴年长者、参与环保活动或协助残障人士，让年轻人在实践中培养公民意识和回馈社会的精神。' },
    ],
  },
  {
    topic: '友情、责任与公民意识',
    color: '#16a085',
    tip: 'The most impressive civic answers move from "rules" to "values" — argue that a good citizen acts rightly even when no one is watching or the law doesn\'t require it. Total Defence\'s 5 pillars is a strong structural device.',
    examples: [
      { text: '新加坡男性公民须服<b>全职国民服役（National Service）</b>，这不仅是保卫国家的军事义务，更是培养年轻人纪律意识、团队精神和牺牲奉献精神的重要历程，是公民责任意识最具体的体现之一。' },
      { text: '每年2月15日是<b>全民防御日（Total Defence Day）</b>，提醒国人保持警惕。全民防御涵盖军事、民事、经济、社会和心理防御<b>五个层面</b>，强调每个公民都是国家安全网络不可或缺的一部分。' },
      { text: '新加坡诈骗案逐年攀升，许多年长者因不熟悉科技而蒙受巨大损失。政府强调，防骗不能只靠警察，更需要全社会<b>「守望相助」</b>——年轻人有责任主动教导长辈识别钓鱼短信，将「独善其身」升华为「兼济天下」。' },
      { text: '新加坡于2021年通过《保护网络骚扰法令》修订，将蓄意公布他人个人资料（<b>「人肉搜索」Doxing</b>）列为刑事罪行，正式确认网络世界并非法外之地，网民须为自己的言行负上法律责任。' },
      { text: '善待服务人员不仅是个人修养的体现，更是我们对维持社会运转的劳动者应尽的责任。政府推行<b>渐进式薪金模式（Progressive Wage Model）</b>，强制要求清洁、安保、餐饮等行业随员工技能提升而逐步提高薪资。' },
    ],
  },
  {
    topic: '小人物大贡献',
    color: '#34495e',
    tip: 'ONE well-told real story beats three generic points. The 曾喆/911 story is your best anchor — tell it in detail. After the story, pivot: greatness is about choices, not status. Then connect to the everyday heroes around us.',
    examples: [
      { text: '<b>曾喆</b>原本只是一名在纽约工作的普通新加坡保险公司职员。2001年9月11日，他在世贸中心遭受恐怖袭击时，选择留下来协助同事逃生，最终不幸罹难。他的牺牲告诉我们：<b>伟大不需要特殊的身份或地位，关键时刻的善良选择，才是定义一个人伟大之处的真正标准</b>。' },
      { text: '每当我们安然入睡，<b>地铁深夜维修人员</b>已深入隧道，清洗车厢、更换轨道、检查信号系统，确保数百万乘客翌日能安全出行。他们的贡献鲜少见报，却是城市正常运转不可或缺的支柱。' },
      { text: '新加坡防止虐待动物协会（SPCA）设有<b>「企业健康计划」</b>，安排曾被遗弃的动物到企业工作场所进行互动探访。这既提升了动物被领养的机会，也让员工在与动物互动的过程中缓解压力、促进心理健康。' },
      { text: '蒙福关爱（Montfort Care）在马林台组屋底层设立<b>「快乐厨房」（Goodlife Makan）</b>，为独居年长者提供共享社区厨房，让他们在一起煮饭、吃饭的过程中结交邻居、建立感情，以一顿饭的温度对抗孤独。' },
      { text: '武吉巴督<b>JamPacked食物银行</b>的义工们默默将市民捐来的食物分门别类，再让低收入家庭用礼券「购物」自取所需。他们的付出不轰动、不显眼，却是许多家庭每个月温饱的保障。' },
    ],
  },
  {
    topic: '创新与建筑',
    color: '#9b59b6',
    tip: 'Describe the design detail AND the problem it solves — that makes your answer insightful rather than encyclopaedic. The NTU Hive passive cooling system is a detail most students don\'t know and will impress an examiner.',
    examples: [
      { text: '南洋理工大学的<b>The Hive教学楼</b>外形酷似广式小笼包，但其创新之处在于「<b>被动置换冷气系统</b>」——通过地板下的管道释放冷水降温，冷空气自然下沉，热空气从无顶盖的中庭散出，节能率极高，体现了「形式服务于功能」的建筑精神。' },
      { text: '<b>Oasia Hotel Downtown</b>外墙攀爬着21种不同的藤蔓植物，<b>绿容率高达1100%</b>，为城市提供的绿化面积是其占地面积的11倍；建筑中央镂空设计让整栋大楼全靠天然穿堂风保持凉爽，无需空调。' },
      { text: '<b>皮克林宾乐雅酒店（Parkroyal Collection Pickering）</b>外墙布满梯田式空中花园，花园的灌溉与照明全靠太阳能电池板和雨水收集系统维持，真正实现了「<b>零能耗空中花园</b>」，并显著降低市中心的热岛效应。' },
      { text: '<b>国家美术馆</b>由两栋历史建筑——前最高法院和前市政厅——翻新改建而成，在保留殖民地时期宏伟外观的同时，内部空间被赋予全新的艺术展览功能。这正是「活化」而非「冰封」历史的最佳诠释。' },
      { text: '近年来，<b>复古文化</b>在本地年轻人中掀起热潮，他们在复古市集中展示个人收藏与融合东南亚元素的创意设计，将娘惹图案、殖民地建筑美学等本土传统转化为现代文创产品，让传统文化以年轻人喜欢的方式延续生命力。' },
    ],
  },
  {
    topic: '动物保护',
    color: '#2ecc71',
    tip: 'SPCA is the anchor organisation here. The Cat Sterilisation Programme is a concrete policy detail. Be specific about what SPCA actually does — "protect animals" is too vague to score.',
    examples: [
      { text: '<b>新加坡防止虐待动物协会（SPCA）</b>成立于1876年，是一个非营利动物保护组织，经费主要来自善心人士捐款。其使命是保护被遗弃的动物，防止虐待，并通过教育宣传塑造一个关爱善待动物的新加坡社会。' },
      { text: 'SPCA将每个月最后一个星期五定为<b>「猫咪星期五」</b>，在上午11点至下午3点期间开放公众领养猫咪。协会会进行严格筛选，确保领养者家中已备妥食物、垃圾箱、玩具和床等必需品，防止弃养事件的发生。' },
      { text: 'SPCA推出<b>「企业健康计划」</b>，安排曾被遗弃的动物到企业工作场所探访，既帮助动物社交化、提高被领养的机会，也让员工在与动物互动中促进心理健康。对于不适合动物探访的工作场所，则提供企业参观SPCA的替代选项。' },
      { text: '新加坡兽医局（AVS）推行<b>社区猫咪绝育计划（Cat Sterilisation Programme）</b>，资助为流浪猫进行绝育手术，通过人道方式有效控制流浪猫数量，减少居民投诉，同时降低猫咪在街头受伤或患病的风险。' },
      { text: '关爱动物不只是爱猫爱狗——它也是对生命的尊重。当我们善待那些无法为自己发声的生命时，我们也在培养一种<b>推己及物的同理心</b>，这种同理心同样适用于我们对待身边的人。' },
    ],
  },
  {
    topic: '爱的表达与家庭',
    color: '#e8b84b',
    tip: 'For family topics, the kite metaphor (管教松紧) and the dual-income challenge are your two structural anchors. The Montfort Care / Goodlife Makan example bridges family and community care neatly.',
    examples: [
      { text: '爱需要言语滋润，否则容易产生隔阂。研究显示，不同的人有不同的<b>「爱的语言」</b>——有人偏好言语肯定，有人偏好实际行动（如准备礼物、花时间陪伴、拥抱）。了解对方的「爱的语言」，才能让爱真正被感受到。' },
      { text: '管教孩子如放风筝：<b>线握得太紧，风筝飞不高；线放得太松，风筝就会失控坠落</b>。这个比喻道出了家庭教育中「管教的度」最难拿捏的地方——既要给孩子空间成长，又要给予足够的方向与保护。' },
      { text: '<b>双薪家庭</b>面临的两大教育挑战：一是把教育责任「外包」给补习中心或托管机构，缺乏亲子互动；二是以网络和AI代替陪伴，孩子的情感需求得不到满足。研究一再提醒我们：陪伴的质量比时间的长短更重要。' },
      { text: '真正的孝道不只是物质上的供养，更重要的是精神上的关怀与陪伴。古人所说的<b>「犬马之养」</b>——只给食物却缺乏情感——正是孝道最应避免的状态。「树欲静而风不止，子欲养而亲不待」，孝道不能等。' },
      { text: '蒙福关爱（Montfort Care）设立的<b>「快乐厨房」（Goodlife Makan）</b>，让独居年长者在共享社区厨房里一起煮饭、吃饭，以一顿饭的温度重建家庭般的社群连结，印证了「陪伴」是任何物质都无法取代的需求。' },
    ],
  },
  {
    topic: '假信息与网络责任',
    color: '#c0392b',
    tip: 'POFMA is Singapore\'s specific legal tool — naming it is far stronger than just saying "the government fights fake news". Connect deepfakes to the broader digital literacy argument for maximum relevance.',
    examples: [
      { text: '新加坡于2019年通过<b>《防止网络假信息和网络操纵法令》（POFMA）</b>，授权部长要求平台或个人更正或下架虚假陈述，并可对蓄意传播假信息者提出检控，是亚洲最早将打击假信息法制化的国家之一。' },
      { text: '<b>Deepfake（深伪）技术</b>能制作以假乱真的AI合成视频，若网民因轻信而随手转发，便可能在不知情的情况下成为诈骗集团或政治操纵的「无心帮凶」，这凸显了提升<b>数码素养（Digital Literacy）</b>的迫切性。' },
      { text: '假信息最大的危害，在于它会<b>破坏人与人之间的信任</b>，在多元种族社会中引发不必要的恐慌甚至种族矛盾。新加坡的多元文化稳定，建立在信任之上，一旦信任瓦解，后果将难以弥补。' },
      { text: '新加坡媒体素养理事会（MLC）推行<b>「SIFT」核实框架</b>（Stop停一停, Investigate调查来源, Find寻找证据, Trace溯源），教导国人在转发信息前先进行四步验证，养成「先核实、再转发」的数码公民习惯。' },
      { text: '在信息爆炸的时代，转发一条未经核实的信息，看似无害，却可能对当事人造成不可挽回的名誉损害，甚至引发「网络私刑」。<b>核实比转发更重要</b>——这是每个网民最基本的道德责任。' },
    ],
  },
  {
    topic: '新加坡的国际联系',
    color: '#2980b9',
    tip: 'This topic rewards showing that Singapore\'s strength comes from embracing difference, not despite it. Bilingualism as a bridge and the hawker culture UNESCO listing both show international-local fusion. Link to economic relevance too.',
    examples: [
      { text: '新加坡推行<b>双语政策</b>，学生须学习英语和自己的母语（华语、马来语或泰米尔语）。英语作为主要交流语言，让新加坡能与全球接轨；而母语教育帮助国人保留文化根基，成为东西方世界之间真正的桥梁。' },
      { text: '新加坡在2015年被<b>联合国教科文组织评为「创意城市设计之都」</b>，证明一个小国也可以凭借多元文化的融合与创意产业的发展，在国际舞台上树立独特的文化品牌。' },
      { text: '新加坡积极推动<b>智慧国（Smart Nation）建设</b>，透过发展数码政府、数码经济、数码社会，以及投资人工智能和5G网络，全面推动数码发展，在全球科技竞争中保持领先。' },
      { text: '作为自由贸易港，新加坡汇聚了全球各地的人才、资本和文化，正是这种<b>「开放的DNA」</b>让新加坡在面积不足800平方公里的土地上，建立起在全球具有举足轻重影响力的经济体系。' },
      { text: '新加坡的<b>多元种族文化（华、马、印、欧）</b>并非只是国内事务，更是对外交往的软实力——我们能与中国、东南亚、印度、西方世界都保持密切的文化和经贸联系，这种多元性是我们独一无二的竞争优势。' },
    ],
  },
];
